var app = angular.module('app', []);

app.controller("HelloWorldCtrl", function ($scope) {
    $scope.months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"].reverse();
    $scope.dates = [new Date("01/01/2019"), new Date("12/2/2019"), new Date("10/3/2019"), new Date("7/21/2019"), new Date("4/18/2019"), new Date("09/12/2019"), new Date("10/19/2019"), new Date("01/04/2019"), new Date("12/29/2019")];

    //  $scope.dates = [new Date("01/01/2019"), new Date("01/03/2019")];

    // $scope.dates=[];
    // for(var i=1;i<=30;i++){
    //     var d = new Date("01/"+i+"/2019");
    //     $scope.dates.push(d);
    // }



    $scope.dates.sort(function (a, b) {
        return a.getTime() - b.getTime();
    })
    $scope.curryear = "2019";
    $scope.processedDates = [];

    var dates = $scope.dates;
    // console.log(dates.length);

    for (var i = 0; i < dates.length; i++) {
        var temp = [], cnt = 0, groupingFactor = 3;
        temp.push(dates[i]);
        for (var j = i + 1; j < dates.length; j++) {
            // console.log(dates[i].toDateString().substring(4),dates[j].toDateString().substring(4));
            // console.log(Math.abs(dates[i].getTime() - dates[j].getTime()) / 86400000);
            if (Math.abs(dates[i].getTime() - dates[j].getTime()) / 86400000 <= groupingFactor - 1) {
                temp.push(dates[j]); cnt++;
            } else break;
        }
        i += cnt;
        $scope.processedDates.push(temp);
    }

    // console.log($scope.processedDates);

    $scope.getStyle = function (date) {
        // console.log(date);
        var diff = Math.abs(new Date("01/01/" + $scope.curryear).getTime() - date.getTime());
        var diffDay = diff / (86400000);
        if (diffDay == 364) diffDay = 365;
        if (diffDay == 1) diffDay = 0;
        diffDay = 365 - diffDay;
        // console.log(diffDay);
        var percent = (diffDay * 100) / 365;
        // console.log(percent);
        if (percent < 50)
            return {
                "top": percent + "%"
            }
        else return {
            "bottom": (100 - percent) + "%"
        }
    }
});

app.controller("account", function ($scope) {
    $scope.account = {
        "id": "1-AJJZE",
        "master_acc_id": "1-AJJZE",
        "master_acc_num": "850052431",
        "created": "2014-03-28 17:33:21",
        "created_by": "SADMIN",
        "updated": "2015-12-01 10:17:16",
        "updated_by": "SADMIN",
        "conflict_id": "0",
        "modification_num": 47,
        "account_nr": "850052431",
        "account_name": "Damme Ievis",
        "account_type": "Residential",
        "account_type_lic": "Residential",
        "account_sub_type": "Standard",
        "account_sub_type_lic": "Residential",
        "ssn_nr": "3807344ddfsdas",
        "account_class": "Customer",
        "account_class_lic": "Customer",
        "primary_contact_id": "1-AJJY6",
        "source": "Siebel",
        "brand": "",
        "secret_question": "",
        "secret_answer": "",
        "good_standing": "Y",
        "account_status_db": "Active",
        "account_status": "Active",
        "account_status_lic": "Active",
        "bankruptcy_date": "",
        "treatment_start_dt": "",
        "bad_debt": "N",
        "secret_cust_acc": "N",
        "insolvency_status": "",
        "insolvency_status_lic": "",
        "credit_class": "",
        "credit_scoring_date": "",
        "customer_since": "2014-03-28",
        "disable_legal_update": "N",
        "primary_postpaid_segment": "Develop",
        "group_id": "",
        "primary_contact_ssn": "3807344ddfsdas",
        "primary_contact_full_name": "Damme Ievis",
        "email_address": "111@domain.com",
        "secondary_email_address": "",
        "primary_phone_nr": "37126879281",
        "primary_contact_mobile_nr": "37121851160",
        "primary_contact_first_name": "Damme",
        "primary_contact_middle_name": "",
        "primary_contact_last_name": "Ievis",
        "primary_contact_salutation": "",
        "full_addr": "Brivibai, 13, a, LT-1234, Vilnius",
        "primary_street_address": "Brivibai",
        "primary_street_nr": "13",
        "primary_street_letter": "a",
        "primary_adress_zip_code": "LT-1234",
        "primary_address_city": "Vilnius",
        "primary_address_country_lic": "Lebanon",
        "primary_address_country": "Lebanon",
        "primary_apartment_nr": "",
        "attention_of": "",
        "care_of": "",
        "primary_address_id": "1-1XBDN",
        "primary_address_latitude": "",
        "primary_address_longitude": "",
        "primary_address_county": "Kanaada",
        "primary_address_parish": "test",
        "primary_address_village": "test",
        "agreement_nr": "",
        "agreement_type": "",
        "agreement_name": "",
        "account_loyalty": "",
        "account_credit_limit": "",
        "vat_number": "",
        "tax_class_lic": "",
        "tax_class": "",
        "is_pure_legacy": "N"
    };
});

app.controller("assets", function ($scope) {
    $scope.assets = [
        {
            "id": "1-2ULHKG",
            "created": "2014-10-06 16:59:31",
            "created_date": "2014-10-06",
            "created_by": "SADMIN",
            "updated": "2014-11-05 13:50:25",
            "updated_by": "TEST_ROLE_2",
            "conflict_id": "0",
            "modification_num": 2,
            "integration_id": "1-2ULTII",
            "owner_account_id": "1-AJJZE",
            "status_lic": "Active",
            "status": "Active",
            "planned_disconnect": "",
            "reactivation_date": "",
            "actual_disconnect_date": "",
            "billing_account_id": "1-2TIZIT",
            "brand": "Tele2",
            "pending_order_id": "1-349NNH",
            "pending_order": "true",
            "follow_on_action": "",
            "follow_on_date": "",
            "alias": "",
            "password": "",
            "wcs_admin_flag": "N",
            "barring_status": "",
            "barring_status_lic": "",
            "binding_start": "",
            "binding_end": "",
            "binding_until_dt": "",
            "billing_account_name": "Damme Ievis",
            "billing_account_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_number": "850143285",
            "billing_legacy_account": "",
            "product_name": "Mobile broad band services",
            "product_type_lic": "MBB",
            "enable_gui_modification": "Y",
            "enable_gui_deactivation": "Y",
            "enable_gui_suspension": "Y",
            "role_based_ordering": "N",
            "price_type": "Recurring",
            "primary_attribute_name": "Postpaid TN",
            "root_pav": "37099816234",
            "primary_attribute_value": "37099816234",
            "regret_end_date": "2014-10-06 16:57:24",
            "status_area": "",
            "activation_date": "",
            "subcomponents": [
                {
                    "id": "1-2ULHKN",
                    "product_sales_category_lic": "Price Plan",
                    "version_date": "2014-10-06 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "Mobile Internet 9 (2,60658 Eur)",
                    "product_type_lic": "Price Plan",
                    "primary_attribute_value": "",
                    "activation_date": "2014-10-06"
                }
            ]
        },
        {
            "id": "1-2W6R8Q",
            "created": "2014-10-20 13:54:06",
            "created_date": "2014-10-20",
            "created_by": "SADMIN",
            "updated": "2014-10-20 13:54:07",
            "updated_by": "SADMIN",
            "conflict_id": "0",
            "modification_num": 1,
            "integration_id": "1-2W6SRH",
            "owner_account_id": "1-AJJZE",
            "status_lic": "Active",
            "status": "Active",
            "planned_disconnect": "",
            "reactivation_date": "",
            "actual_disconnect_date": "",
            "billing_account_id": "1-2TIZIT",
            "brand": "Tele2",
            "pending_order_id": "",
            "pending_order": "false",
            "follow_on_action": "",
            "follow_on_date": "",
            "alias": "",
            "password": "",
            "wcs_admin_flag": "N",
            "barring_status": "",
            "barring_status_lic": "",
            "binding_start": "",
            "binding_end": "",
            "binding_until_dt": "",
            "billing_account_name": "Damme Ievis",
            "billing_account_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_number": "850143285",
            "billing_legacy_account": "",
            "product_name": "Mobile broad band services",
            "product_type_lic": "MBB",
            "enable_gui_modification": "Y",
            "enable_gui_deactivation": "Y",
            "enable_gui_suspension": "Y",
            "role_based_ordering": "N",
            "price_type": "Recurring",
            "primary_attribute_name": "Postpaid TN",
            "root_pav": "37098234097",
            "primary_attribute_value": "37098234097",
            "regret_end_date": "2014-10-20 13:41:07",
            "status_area": "",
            "activation_date": "2014-10-20",
            "subcomponents": [
                {
                    "id": "1-2W6RA7",
                    "product_sales_category_lic": "Price Plan",
                    "version_date": "2014-10-20 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "Laisvas internetas XL (45 LT) (13,0329 Eur)",
                    "product_type_lic": "Price Plan",
                    "primary_attribute_value": "",
                    "activation_date": "2014-10-20"
                },
                {
                    "id": "1-2W6R8U",
                    "product_sales_category_lic": "SIM Card",
                    "version_date": "2014-10-20 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "SIM card",
                    "product_type_lic": "SIM Card",
                    "primary_attribute_value": "76895463465345646566",
                    "activation_date": "2014-10-20"
                }
            ]
        },
        {
            "id": "1-2W6P0N",
            "created": "2014-10-20 13:54:06",
            "created_date": "2014-10-20",
            "created_by": "SADMIN",
            "updated": "2014-10-20 13:54:06",
            "updated_by": "SADMIN",
            "conflict_id": "0",
            "modification_num": 1,
            "integration_id": "1-2W6NMM",
            "owner_account_id": "1-AJJZE",
            "status_lic": "Active",
            "status": "Active",
            "planned_disconnect": "",
            "reactivation_date": "",
            "actual_disconnect_date": "",
            "billing_account_id": "1-2TIZIT",
            "brand": "Tele2",
            "pending_order_id": "",
            "pending_order": "false",
            "follow_on_action": "",
            "follow_on_date": "",
            "alias": "",
            "password": "",
            "wcs_admin_flag": "N",
            "barring_status": "",
            "barring_status_lic": "",
            "binding_start": "",
            "binding_end": "",
            "binding_until_dt": "",
            "billing_account_name": "Damme Ievis",
            "billing_account_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_number": "850143285",
            "billing_legacy_account": "",
            "product_name": "Mobile broad band services",
            "product_type_lic": "MBB",
            "enable_gui_modification": "Y",
            "enable_gui_deactivation": "Y",
            "enable_gui_suspension": "Y",
            "role_based_ordering": "N",
            "price_type": "Recurring",
            "primary_attribute_name": "Postpaid TN",
            "root_pav": "37034187645",
            "primary_attribute_value": "37034187645",
            "regret_end_date": "2014-10-20 13:41:07",
            "status_area": "",
            "activation_date": "2014-10-20",
            "subcomponents": [
                {
                    "id": "1-2W6P0R",
                    "product_sales_category_lic": "SIM Card",
                    "version_date": "2014-10-20 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "SIM card",
                    "product_type_lic": "SIM Card",
                    "primary_attribute_value": "78965460786756634633",
                    "activation_date": "2014-10-20"
                },
                {
                    "id": "1-2W6P10",
                    "product_sales_category_lic": "Price Plan",
                    "version_date": "2014-10-20 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "Mobile Internet S (2,60658 Eur)",
                    "product_type_lic": "Price Plan",
                    "primary_attribute_value": "",
                    "activation_date": "2014-10-20"
                }
            ]
        },
        {
            "id": "1-2W6P0N",
            "created": "2014-10-20 13:54:06",
            "created_date": "2014-10-20",
            "created_by": "SADMIN",
            "updated": "2014-10-20 13:54:06",
            "updated_by": "SADMIN",
            "conflict_id": "0",
            "modification_num": 1,
            "integration_id": "1-2W6NMM",
            "owner_account_id": "1-AJJZE",
            "status_lic": "Active",
            "status": "Active",
            "planned_disconnect": "",
            "reactivation_date": "",
            "actual_disconnect_date": "",
            "billing_account_id": "1-2TIZIT",
            "brand": "Tele2",
            "pending_order_id": "",
            "pending_order": "false",
            "follow_on_action": "",
            "follow_on_date": "",
            "alias": "",
            "password": "",
            "wcs_admin_flag": "N",
            "barring_status": "",
            "barring_status_lic": "",
            "binding_start": "",
            "binding_end": "",
            "binding_until_dt": "",
            "billing_account_name": "Damme Ievis",
            "billing_account_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_number": "850143285",
            "billing_legacy_account": "",
            "product_name": "Mobile broad band services",
            "product_type_lic": "MBB",
            "enable_gui_modification": "Y",
            "enable_gui_deactivation": "Y",
            "enable_gui_suspension": "Y",
            "role_based_ordering": "N",
            "price_type": "Recurring",
            "primary_attribute_name": "Postpaid TN",
            "root_pav": "37034187645",
            "primary_attribute_value": "37034187645",
            "regret_end_date": "2014-10-20 13:41:07",
            "status_area": "",
            "activation_date": "2014-10-20",
            "subcomponents": [
                {
                    "id": "1-2W6P0R",
                    "product_sales_category_lic": "SIM Card",
                    "version_date": "2014-10-20 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "SIM card",
                    "product_type_lic": "SIM Card",
                    "primary_attribute_value": "78965460786756634633",
                    "activation_date": "2014-10-20"
                },
                {
                    "id": "1-2W6P10",
                    "product_sales_category_lic": "Price Plan",
                    "version_date": "2014-10-20 00:00:00",
                    "ba_id": "1-2TIZIT",
                    "status_lic": "Active",
                    "product_name": "Mobile Internet S (2,60658 Eur)",
                    "product_type_lic": "Price Plan",
                    "primary_attribute_value": "",
                    "activation_date": "2014-10-20"
                }
            ]
        }


    ]
});

app.controller("orders", function ($scope) {
    $scope.orders = [
        {
            "id": "1-349NNH",
            "created": "2014-11-05 13:50:23",
            "created_by": "TEST_ROLE_2",
            "updated": "2014-11-05 13:50:23",
            "updated_by": "TEST_ROLE_2",
            "conflict_id": "0",
            "modification_num": 0,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "1-2TIZIT",
            "ba_name": "Damme Ievis",
            "ba_number": "850143285",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-11-05",
            "order_datetime": "2014-11-05 13:50:23",
            "order_number": "1-188567549",
            "order_type_lic": "Change Order",
            "order_type": "Modify Order",
            "status_lic": "New",
            "status": "New",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "Residential",
            "order_ba_type": "Residential",
            "order_ba_subtype_lic": "Residential",
            "order_ba_subtype": "Standard",
            "external_order_id": "",
            "contact_id": "1-AJJY8",
            "last_name": "Ln1xml_KsDPDt9",
            "contact_full_name": "Fn1xml_CqUwTsZ1 Ln1xml_KsDPDt9",
            "sales_channel": "Customer Service"
        },
        {
            "id": "1-2W6NG6",
            "created": "2014-10-20 13:41:07",
            "created_by": "TEST_ROLE_8",
            "updated": "2014-10-20 13:54:03",
            "updated_by": "EAIADMIN",
            "conflict_id": "0",
            "modification_num": 13,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "1-2TIZIT",
            "ba_name": "Damme Ievis",
            "ba_number": "850143285",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-10-20",
            "order_datetime": "2014-10-20 13:41:07",
            "order_number": "1-174990390",
            "order_type_lic": "Sales Order",
            "order_type": "Sales Order",
            "status_lic": "Complete",
            "status": "Complete",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "Residential",
            "order_ba_type": "Residential",
            "order_ba_subtype_lic": "Residential",
            "order_ba_subtype": "Standard",
            "external_order_id": "",
            "contact_id": "1-AJJYA",
            "last_name": "LNAdditional3IZkGZKz",
            "contact_full_name": "FNAdditional3sMYEDIP LNAdditional3IZkGZKz",
            "sales_channel": "Customer Service"
        },
        {
            "id": "1-2ULTGF",
            "created": "2014-10-06 16:57:24",
            "created_by": "TEST_ROLE_8",
            "updated": "2014-10-06 16:59:29",
            "updated_by": "EAIADMIN",
            "conflict_id": "0",
            "modification_num": 10,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "1-2TIZIT",
            "ba_name": "Damme Ievis",
            "ba_number": "850143285",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-10-06",
            "order_datetime": "2014-10-06 16:57:24",
            "order_number": "1-172338783",
            "order_type_lic": "Sales Order",
            "order_type": "Sales Order",
            "status_lic": "Complete",
            "status": "Complete",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "Residential",
            "order_ba_type": "Residential",
            "order_ba_subtype_lic": "Residential",
            "order_ba_subtype": "Standard",
            "external_order_id": "",
            "contact_id": "1-AJJY8",
            "last_name": "Ln1xml_KsDPDt9",
            "contact_full_name": "Fn1xml_CqUwTsZ1 Ln1xml_KsDPDt9",
            "sales_channel": "Customer Service"
        },
        {
            "id": "1-2NO1UK",
            "created": "2014-09-02 08:50:30",
            "created_by": "TEST_ROLE_2",
            "updated": "2014-09-02 08:50:39",
            "updated_by": "TEST_ROLE_2",
            "conflict_id": "0",
            "modification_num": 2,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "",
            "ba_name": "",
            "ba_number": "",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-09-02",
            "order_datetime": "2014-09-02 08:50:30",
            "order_number": "1-160685660",
            "order_type_lic": "Sales Order",
            "order_type": "Sales Order",
            "status_lic": "New",
            "status": "New",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "",
            "order_ba_type": "",
            "order_ba_subtype_lic": "",
            "order_ba_subtype": "",
            "external_order_id": "",
            "contact_id": "1-AJJY8",
            "last_name": "Ln1xml_KsDPDt9",
            "contact_full_name": "Fn1xml_CqUwTsZ1 Ln1xml_KsDPDt9",
            "sales_channel": "Customer Service"
        },
        {
            "id": "1-2M4BZ8",
            "created": "2014-08-01 14:58:51",
            "created_by": "TEST_ROLE_8",
            "updated": "2014-08-01 15:15:19",
            "updated_by": "TEST_ROLE_8",
            "conflict_id": "0",
            "modification_num": 4,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "",
            "ba_name": "",
            "ba_number": "",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-08-01",
            "order_datetime": "2014-08-01 14:58:51",
            "order_number": "1-158086052",
            "order_type_lic": "Sales Order",
            "order_type": "Sales Order",
            "status_lic": "New",
            "status": "New",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "",
            "order_ba_type": "",
            "order_ba_subtype_lic": "",
            "order_ba_subtype": "",
            "external_order_id": "",
            "contact_id": "1-AJJY8",
            "last_name": "Ln1xml_KsDPDt9",
            "contact_full_name": "Fn1xml_CqUwTsZ1 Ln1xml_KsDPDt9",
            "sales_channel": "Customer Service"
        },
        {
            "id": "1-1DQFVT",
            "created": "2014-07-10 10:13:23",
            "created_by": "TEST_ROLE_8",
            "updated": "2014-07-10 10:14:12",
            "updated_by": "TEST_ROLE_8",
            "conflict_id": "0",
            "modification_num": 1,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "1-AJJZJ",
            "ba_name": "Damme Ievis",
            "ba_number": "850052444",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-07-10",
            "order_datetime": "2014-07-10 10:13:23",
            "order_number": "1-83534825",
            "order_type_lic": "Sales Order",
            "order_type": "Sales Order",
            "status_lic": "New",
            "status": "New",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "Residential",
            "order_ba_type": "Residential",
            "order_ba_subtype_lic": "Residential",
            "order_ba_subtype": "Standard",
            "external_order_id": "",
            "contact_id": "1-AJJY8",
            "last_name": "Ln1xml_KsDPDt9",
            "contact_full_name": "Fn1xml_CqUwTsZ1 Ln1xml_KsDPDt9",
            "sales_channel": "Customer Service"
        },
        {
            "id": "1-AJK11",
            "created": "2014-03-28 17:33:23",
            "created_by": "SADMIN",
            "updated": "2014-03-28 17:33:33",
            "updated_by": "SADMIN",
            "conflict_id": "0",
            "modification_num": 4,
            "active_flg": "Y",
            "revision": 1.0,
            "ba_id": "1-AJJZJ",
            "ba_name": "Damme Ievis",
            "ba_number": "850052444",
            "ca_id": "1-AJJZE",
            "ca_nr": "850052431",
            "order_acc_class_lic": "Customer",
            "order_acc_class": "Customer",
            "order_date": "2014-03-28",
            "order_datetime": "2014-03-28 17:33:13",
            "order_number": "1-17708581",
            "order_type_lic": "",
            "order_type": "",
            "status_lic": "Open",
            "status": "Open",
            "shipping_method_lic": "Postal parcel",
            "shipping_method": "Postal parcel",
            "order_ba_type_lic": "Residential",
            "order_ba_type": "Residential",
            "order_ba_subtype_lic": "Residential",
            "order_ba_subtype": "Standard",
            "external_order_id": "CallerV26zaNGxUU",
            "contact_id": "1-AJJY8",
            "last_name": "Ln1xml_KsDPDt9",
            "contact_full_name": "Fn1xml_CqUwTsZ1 Ln1xml_KsDPDt9",
            "sales_channel": "Telemarketing"
        }
    ]
});

app.controller("invoices", function ($scope) {
    $scope.invoices = [
        {
            "billing_status": "Active",
            "billing_class": "Billing",
            "billing_treatment_start": "",
            "billing_account_nr": "850143285",
            "billing_account_type": "Residential",
            "billing_account_sub_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_name": "Damme Ievis",
            "ba_id": "1-2TIZIT",
            "ba_primary_contact_phone": "37121851160",
            "ba_primary_contact_email": "111@domain.com",
            "invoice_system": "Singl.eView",
            "ocr_nr": "70437711",
            "invoice_nr": "70437711",
            "invoice_id": "70437711",
            "id": "70437711",
            "total_amount": "10.0",
            "total_amount_VAT": "0.0",
            "invoice_excl_vat_amt": "0.0",
            "invoice_incl_vat_amt": "",
            "invoice_date": "2014-05-01 00:00:00",
            "due_date": "2014-05-25 00:00:00",
            "invoice_hold_date": "",
            "invoice_code": "Standard",
            "outstanding_amount": "0.0",
            "pending_reprint": "N",
            "treatment_amount": "",
            "treatment_status": "",
            "treatment_status_lic": "",
            "treatment_level": "",
            "treatment_entered_date": "",
            "dispute_expiry_date": "",
            "dispute_type_lic": "",
            "dispute_reason_lic": "",
            "status": "Paid",
            "status_lic": "Paid",
            "invoice_cut_off_date": "",
            "dispute": "N"
        },
        {
            "billing_status": "Active",
            "billing_class": "Billing",
            "billing_treatment_start": "",
            "billing_account_nr": "850143285",
            "billing_account_type": "Residential",
            "billing_account_sub_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_name": "Damme Ievis",
            "ba_id": "1-2TIZIT",
            "ba_primary_contact_phone": "37121851160",
            "ba_primary_contact_email": "111@domain.com",
            "invoice_system": "Singl.eView",
            "ocr_nr": "69200008",
            "invoice_nr": "69200008",
            "invoice_id": "69200008",
            "id": "69200008",
            "total_amount": "",
            "total_amount_VAT": "0.0",
            "invoice_excl_vat_amt": "0.0",
            "invoice_incl_vat_amt": "",
            "invoice_date": "2014-04-01 00:00:00",
            "due_date": "2014-04-25 00:00:00",
            "invoice_hold_date": "",
            "invoice_code": "Standard",
            "outstanding_amount": "0.0",
            "pending_reprint": "N",
            "treatment_amount": "",
            "treatment_status": "",
            "treatment_status_lic": "",
            "treatment_level": "",
            "treatment_entered_date": "",
            "dispute_expiry_date": "",
            "dispute_type_lic": "",
            "dispute_reason_lic": "",
            "status": "Paid",
            "status_lic": "Paid",
            "invoice_cut_off_date": "",
            "dispute": "N"
        },
        {
            "billing_status": "Active",
            "billing_class": "Billing",
            "billing_treatment_start": "",
            "billing_account_nr": "850143285",
            "billing_account_type": "Residential",
            "billing_account_sub_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_name": "Damme Ievis",
            "ba_id": "1-2TIZIT",
            "ba_primary_contact_phone": "37121851160",
            "ba_primary_contact_email": "111@domain.com",
            "invoice_system": "Singl.eView",
            "ocr_nr": "67364363",
            "invoice_nr": "67364363",
            "invoice_id": "67364363",
            "id": "67364363",
            "total_amount": "",
            "total_amount_VAT": "0.0",
            "invoice_excl_vat_amt": "0.0",
            "invoice_incl_vat_amt": "",
            "invoice_date": "2014-02-01 00:00:00",
            "due_date": "2014-02-25 00:00:00",
            "invoice_hold_date": "",
            "invoice_code": "Standard",
            "outstanding_amount": "0.0",
            "pending_reprint": "Y",
            "treatment_amount": "",
            "treatment_status": "",
            "treatment_status_lic": "",
            "treatment_level": "",
            "treatment_entered_date": "",
            "dispute_expiry_date": "",
            "dispute_type_lic": "",
            "dispute_reason_lic": "",
            "status": "Paid",
            "status_lic": "Paid",
            "invoice_cut_off_date": "",
            "dispute": "N"
        },
        {
            "billing_status": "Active",
            "billing_class": "Billing",
            "billing_treatment_start": "",
            "billing_account_nr": "850143285",
            "billing_account_type": "Residential",
            "billing_account_sub_type": "Residential",
            "billing_account_source": "Singl.eView",
            "billing_account_name": "Damme Ievis",
            "ba_id": "1-2TIZIT",
            "ba_primary_contact_phone": "37121851160",
            "ba_primary_contact_email": "111@domain.com",
            "invoice_system": "Singl.eView",
            "ocr_nr": "65749173",
            "invoice_nr": "65749173",
            "invoice_id": "65749173",
            "id": "65749173",
            "total_amount": "",
            "total_amount_VAT": "0.0",
            "invoice_excl_vat_amt": "0.0",
            "invoice_incl_vat_amt": "",
            "invoice_date": "2013-12-01 00:00:00",
            "due_date": "",
            "invoice_hold_date": "2015-05-06 00:00:00",
            "invoice_code": "Standard",
            "outstanding_amount": "",
            "pending_reprint": "N",
            "treatment_amount": "",
            "treatment_status": "",
            "treatment_status_lic": "",
            "treatment_level": "",
            "treatment_entered_date": "",
            "dispute_expiry_date": "2015-04-19 00:00:00",
            "dispute_type_lic": "",
            "dispute_reason_lic": "",
            "status": "In Dispute",
            "status_lic": "In Dispute",
            "invoice_cut_off_date": "",
            "dispute": "Y"
        }
    ]
});